### ISSUE TITLE
no preview?

### ISSUE THREAD

**Issue by diomed** [animaux/simplemde#10]
why is there no image [button] and no preview button?

**Comment by animaux** [comment]
Simply because this is the setup I always use for my clients. Normally I have all images in galleries and no inline-images. 

As for the preview button, I did not find the functionality very useful. 

The ideal solution would be to have the buttons configurable in the field settings. I’m happy to accept a pull request for that `;)`.

**Comment by diomed** [comment]
OK then. gonna use Editor for Symphony for my needs.

**Comment by animaux** [comment]
No problem. You could also simply adjust the config to fit your needs: https://github.com/animaux/simplemde/blob/master/assets/simplemde.publish.js#L19

Options here —> https://github.com/sparksuite/simplemde-markdown-editor#configuration
